server:
  port: 8080
  servlet:
    context-path: /tdla

spring:
  application:
    name: ToDoListAPI
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always

  #DATABASE
  data:
    jpa:
      repositories:
        bootstrap-mode: DEFAULT

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        #format_sql: true
        #user_sql_comments: true
        highlight_sql: true
    #show_sql: true
    open-in-view: false

spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method